---

- name: restart pm2
  shell: "{{ pm2_bin }} restart {{ pm2_procs_file }}"
  args:
    chdir: "{{ pm2_user_home }}"
    executable: /bin/bash
  environment:
    PM2_HOME: "{{ pm2_user_home }}/.pm2"
  become: yes
  become_user: "{{ pm2_user }}"

- name: update pm2
  shell: "{{ pm2_bin }} update"
  args:
    chdir: "{{ pm2_user_home }}"
    executable: /bin/bash
  environment:
    PM2_HOME: "{{ pm2_user_home }}/.pm2"
  become: yes
  become_user: "{{ pm2_user }}"
