---

- name: create ghost user
  user:
    name: ghost
    shell: /usr/sbin/nologin
    state: present

- name: create ghost directory
  file:
    path: "{{ ghost_dir }}"
    owner: deploy
    group: ghost
    mode: "06775"
    state: directory

- name: install ghost
  unarchive:
    src: "https://ghost.org/zip/ghost-latest.zip"
    dest: "{{ ghost_dir }}"
    owner: deploy
    mode: g+w
    copy: no

- name: install ghost dependencies
  npm:
    path: "{{ ghost_dir }}"
    production: yes
    state: present

- name: install bower
  npm:
    name: bower
    global: yes
    state: present
