---
# Heavily inspired by Nodesource's ansible-nodejs-role
# (https://github.com/nodesource/ansible-nodejs-role)

- name: enable apt https transport
  apt:
    name: apt-transport-https
    state: present

- name: add Nodesource apt key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: add Nodesource apt repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ node_deb_repo_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ node_deb_repo_version }} {{ ansible_distribution_release }} main"

- name: install node
  apt:
    name: nodejs
    update_cache: yes
    state: present

- name: install pm2
  npm:
    name: pm2
    global: yes
    state: present

- name: create node user
  user:
    name: node
    shell: /usr/sbin/nologin
    state: present
