---

- name: decrypt secrets
  include_vars: vault.yml
  no_log: yes

- name: install ssl certificate
  copy:
    content: "{{ ssl_cert }}"
    dest: /etc/ssl/certs/{{ domain }}.pem
  become: yes
  notify: restart nginx

- name: install ssl key
  copy:
    content: "{{ ssl_key }}"
    dest: /etc/ssl/private/{{ domain }}.key
    mode: 0600
  become: yes
  notify: restart nginx

- name: configure nginx site
  template:
    src: ghost.j2
    dest: /etc/nginx/sites-available/{{ domain }}
  become: yes
  notify: reload nginx

- name: enable nginx site
  file:
    src: /etc/nginx/sites-available/{{ domain }}
    dest: /etc/nginx/sites-enabled/{{ domain }}
    state: link
  become: yes
  notify: reload nginx
