---

- name: install nginx
  apt:
    name: nginx
    state: present

- name: allow http and https traffic
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { port: http, proto: tcp }
    - { port: https, proto: tcp }

- name: disable nginx default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: make sure nginx is running
  service:
    name: nginx
    enabled: yes
    state: started
