---

# AVAILABLE TAGS
# ==============
# provision: configure droplet and install necessary packages
# upgrade: upgrade all packages (apt)
#   apt-upgrade: perform an `apt-get dist-upgrade`
# ==============
# Each role is also tagged with its name, to allow more granular operations.

- hosts: wintermute
  remote_user: deploy
  roles:
    - { role: common, tags: ['common'] }
    - { role: exim, tags: ['exim'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: node, tags: ['node'] }
