---

- name: set hostname
  hostname:
    name: "{{ hostname }}"

- name: configure hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
  notify: restart networking

- name: install essential packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - fail2ban
    - git
    - logwatch
    - ntp
    - ufw
    - unzip

- name: allow ntp and ssh traffic
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { port: ntp, proto: udp }
    - { port: ssh, proto: tcp }

- name: deny all other traffic
  ufw:
    policy: deny
    state: enabled

- name: configure logwatch
  template:
    src: templates/logwatch.j2
    dest: /etc/logwatch/conf/logwatch.conf

- name: disable ssh password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart sshd

- name: create admin user
  user:
    name: "{{ admin_user }}"
    groups: sudo
    append: yes
    shell: /bin/bash
    state: present

- name: grant ssh access to admin user
  authorized_key:
    user: "{{ admin_user }}"
    key: "{{ lookup('file', admin_pub_key_file) }}"
    state: present

- name: make sure services are shiny
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - exim4
    - fail2ban
    - networking
    - ntp
    - sshd
    - ufw
